# Generated by Django 5.2 on 2025-07-11 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0002_apilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='uniqid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
