# Generated by Django 5.2 on 2025-07-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0003_apilog_uniqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='uniqid',
            field=models.UUIDField(db_index=True, editable=False, unique=True),
        ),
    ]
