# Generated by Django 5.2 on 2025-07-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0004_apilog_session_id_alter_apilog_uniqid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilog',
            name='session_id',
        ),
    ]
