# Generated by Django 5.2 on 2025-07-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0005_remove_apilog_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='uniqid',
            field=models.UUIDField(db_index=True, editable=False),
        ),
    ]
