# Generated by Django 5.2 on 2025-07-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0007_alter_apilog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilog',
            name='response_data',
        ),
    ]
