# Generated by Django 5.2 on 2025-07-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0008_remove_apilog_response_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccountremark',
            name='loan_id',
            field=models.CharField(db_index=True, default=0, max_length=30),
        ),
    ]
