# Generated by Django 5.2 on 2025-07-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0009_loanaccountremark_loan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_text', models.CharField(max_length=255, unique=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Master Remark',
                'verbose_name_plural': 'Master Remarks',
                'db_table': 'master_remarks',
            },
        ),
    ]
