# Generated by Django 5.2 on 2025-07-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0010_masterremark'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masterremark',
            table=None,
        ),
    ]
