# Generated by Django 5.2 on 2025-07-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0011_alter_masterremark_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masterremark',
            table='dedup_master_remarks',
        ),
    ]
