# Generated by Django 5.2 on 2025-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0012_alter_masterremark_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccountremark',
            name='remark',
            field=models.IntegerField(),
        ),
    ]
