# Generated by Django 5.2 on 2025-09-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0013_alter_loanaccountremark_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanaccountremark',
            name='request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
