# Generated by Django 5.2 on 2025-09-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0014_apilog_request_id_loanaccountremark_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilog',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='loanaccountremark',
            name='request_id',
        ),
    ]
