# Generated by Django 5.2 on 2025-09-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0015_remove_apilog_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccountremark',
            name='uniqid',
            field=models.CharField(default='631d399a-3538-47f1-b2bf-eadc708d7914', max_length=255),
            preserve_default=False,
        ),
    ]
