# Generated by Django 5.2 on 2025-09-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0016_loanaccountremark_uniqid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanaccountremark',
            old_name='uniqid',
            new_name='unique_id',
        ),
    ]
