# Generated by Django 5.2 on 2025-09-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0017_rename_uniqid_loanaccountremark_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='uniqid',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
