# Generated by Django 5.2.5 on 2025-08-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_order_no',
        ),
        migrations.RemoveField(
            model_name='role',
            name='api_limit',
        ),
    ]
