# Generated by Django 5.2.5 on 2025-08-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbluser',
            old_name='unique_key',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='login_attempt',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='username',
        ),
    ]
