# Generated by Django 5.2.5 on 2025-08-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_remove_menu_menu_id_remove_menu_menu_order_no_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rolepermission',
            name='unique_role_menu',
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='menu_id',
            field=models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='auth_system.menu'),
        ),
    ]
