# Generated by Django 5.2.5 on 2025-08-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_rename_unique_key_tbluser_key_remove_tbluser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
