# Generated by Django 5.2.5 on 2025-08-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_remove_rolepermission_unique_role_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sort_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
