# Generated by Django 5.2.5 on 2025-08-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_alter_tbluser_created_by_alter_tbluser_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
