# Generated by Django 5.2.5 on 2025-08-13 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_alter_tbluser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
