# Generated by Django 5.2 on 2025-09-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_alter_menu_sort_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'menu_id'), name='unique_role_menu'),
        ),
    ]
