# Generated by Django 5.2.5 on 2025-08-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_alter_tbluser_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
    ]
