# Generated by Django 5.2 on 2025-09-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_rolepermission_unique_role_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='uniqid',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
