# Generated by Django 5.2 on 2025-08-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_alter_tbluser_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackListedToken',
        ),
    ]
