# Generated by Django 5.2 on 2025-08-14 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0008_apilog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
