# Generated by Django 5.2 on 2025-08-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0009_alter_tbluser_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
